# /actors/{actorId} endpoints

is: [ secured ]
type:
  item:
    item: "actor"
    itemSchema: !include schemas/actor.json
    exampleGet: !include examples/actors/actor.get.json
    examplePutBody: !include examples/actors/actor.put.json
    examplePutResponse: !include examples/actors/actor.put.response.json
    idExample: !include examples/actors/actor.id.txt
    idName: actorId
