# /actors/{actorId}/movies endpoints

is: [ secured ]
type:
  attachedCollection:
    mainItems: "movies"
    secondaryItem: "actor"
    collectionSchema: !include schemas/movies.json
    exampleGet: !include examples/movies/movie.get.json
    examplePost: !include examples/movies/movies.post.json
    idExample: !include examples/actors/actor.id.txt
    idName: actorId
