# /actors endpoints

is: [ secured ]
type:
  collection:
    mainItems: "actors"
    collectionSchema: !include schemas/actors.json
    exampleGet: !include examples/actors/actors.get.json
    examplePost: !include examples/actors/actors.post.json
