# /actors/{actorId}/movies/{movieId} endpoints

is: [ secured ]
type:
  attachedItem:
    mainItem: "movie"
    secondaryItem: "actor"    
    itemSchema: !include schemas/movie.json
    exampleGet: !include examples/movies/movie.get.json
    mainIdExample: !include examples/movies/movie.id.txt
    secondaryIdExample: !include examples/actors/actor.id.txt
    mainIdName: movieId
    secondaryIdName: actorId
