# /actors/{actorId}/movies endpoints

is: [ secured ]
type:
  attachedCollection:
    mainItems: "movies"
    secondaryItem: "actor"
    collectionSchema: !include schemas/movies.schema
    exampleGet: !include examples/movies/movie.get.example
    examplePost: !include examples/movies/movies.post.example
    idExample: !include examples/actors/actor.id.example
    idName: actorId
