# /movies/{movieId} endpoints

is: [ secured ]
type:
  item:
    item: "movie"
    itemSchema: !include schemas/movie.schema
    exampleGet: !include examples/movies/movie.get.example
    examplePutBody: !include examples/movies/movie.put.example
    examplePutResponse: !include examples/movies/movie.put.response.example
    idExample: !include examples/movies/movie.id.example
    idName: movieId
