# /movies/{movieId} endpoints

is: [ secured ]
type:
  item:
    item: "movie"
    itemSchema: !include schemas/movie.json
    exampleGet: !include examples/movies/movie.get.json
    examplePutBody: !include examples/movies/movie.put.json
    examplePutResponse: !include examples/movies/movie.put.response.json
    idExample: !include examples/movies/movie.id.txt
    idName: movieId
