# /movies/{movieId}/actors/{actorId} endpoints

is: [ secured ]
type:
  attachedItem:
    mainItem: "actor"
    secondaryItem: "movie"    
    itemSchema: !include schemas/actor.json
    exampleGet: !include examples/actors/actor.get.json
    mainIdExample: !include examples/actors/actor.id.txt
    secondaryIdExample: !include examples/movies/movie.id.txt
    mainIdName: actorId
    secondaryIdName: movieId
