# /movies endpoints

is: [ secured ]
type:
  collection:
    mainItems: "movies"
    collectionSchema: !include schemas/movies.json
    exampleGet: !include examples/movies/movies.get.json
    examplePost: !include examples/movies/movies.post.json
